name: http_service
description: Dart package which manages http.
publish_to: none

environment:
  sdk: ^3.5.2
dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0

  http: ^1.3.0
  authentication_repository:
    path: ../authentication_repository